services:
  apache:
    build:
      context: ./apache
    image: apache_compose_image
    container_name: apache_compose
    volumes:
      - $PROJECT_DIR/nginx/nginx_serv:/var/www/html
    ports:
      - "8080:80"
    networks:
      - my_network


  nginx:
    build:
      context: ./nginx
    image: nginx_compose_image
    container_name: nginx_compose
    environment:
      - EMAIL=${EMAIL}
      - DOMAIN=${DOMAIN}
    volumes:
      - $PROJECT_DIR/nginx/certbot/certs:/etc/letsencrypt:ro                      # Persist Certbot certificates
      - $PROJECT_DIR/nginx/certbot/acme-challenges:/certbot/www:ro                # HTTP-01 challenge storage for Certbot
      - $PROJECT_DIR/nginx/nginx/sites-enabled:/etc/nginx/sites-enabled:ro
      - $PROJECT_DIR/nginx/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - $PROJECT_DIR/nginx/nginx_serv:/sites/starter:ro
    ports:
      - "80:80"
      - "443:443"
      - "8081:8081"
      - "8082:8082"
    depends_on:
      - apache
    networks:
      - my_network
    env_file:
      - .env

networks:
  my_network:
    driver: bridge
